version: '3.8'

networks:
  template-network:
    driver: bridge

services:
  template-backoffice:
    image: 'noephilippe/template-backoffice:latest'
    container_name: template-backoffice
    restart: always
    ports:
      - '3001:3001'
    networks:
      - template-network
