version: '3.8'

networks:
  fast-foodie-network:
    driver: bridge

services:
  fast-foodie:
    image: ${GHCR_REGISTRY}/${OWNER_LC}/fast-foodie:${SHA}
    container_name: fast-foodie
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - fast-foodie-network
