version: '3.8'

networks:
  sakana-san-network:
    driver: bridge

services:
  fast-foodie:
    image: 'noephilippe/fast-foodie:latest'
    container_name: fast-foodie
    restart: always
    ports:
      - '3000:3000'
    networks:
      - sakana-san-network
