version: '3.8'

networks:
  fast-foodie-network:
    driver: bridge

services:
  fast-foodie:
    image: 'noephilippe/fast-foodie:latest'
    container_name: fast-foodie
    restart: always
    env_file: .env
    volumes:
      - files:/app/public/files
    ports:
      - '3000:3000' # Nouveau port hôte pour éviter le conflit avec le backoffice existant
    depends_on:
      - fast-foodie-db
    networks:
      - fast-foodie-network

  fast-foodie-db:
    image: 'postgres:14.5-alpine'
    command: postgres -c 'max_connections=1000'
    container_name: fast-foodie-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_DB=${PG_DATABASE}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '5432:5432' # Nouveau port hôte pour éviter le conflit avec la DB existante
    networks:
      - fast-foodie-network

volumes:
  files:
  db:
