name: CI Tests

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.20

      - name: Install dependencies (bun)
        run: bun install --no-progress

      - name: Run unit tests (Jest via bun)
        run: bun x jest --ci --coverage
